[package]
name = "glossarium"
version = "0.4.2"
entrypoint = "glossarium.typ"
authors = ["slashformotion", "Dherse"]
license = "MIT"
description = "Glossarium is a simple, easily customizable typst glossary."
repository = "https://github.com/typst-community/glossarium"
exclude = [
    "tbump.toml",
    "examples/*",
    "makefile",
    "tests",
    ".gitignore",
    ".github/*",
    ".vscode",
]
